modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="https://github.com/MasterGeneral156/This-Means-War/blob/main/LICENSE"
issueTrackerURL="https://github.com/MasterGeneral156/This-Means-War/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="thismeanswar" #mandatory
version="0.0.3-alpha" #mandatory
displayName="This Means WAR!" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/minecraft/this_means_war.json" #optional
displayURL="https://github.com/MasterGeneral156/This-Means-War" #optional
logoFile="logo.png" #optional
credits="TheMasterGeneral" #optional
authors="TheMasterGeneral" #optional
# The description text for the mod (multi line!) (#mandatory)
description="Its time for war, so lets have some guns, ammo and whatnot."