modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="https://github.com/MasterGeneral156/Mo-Glowstone-Lamps/blob/master/LICENSE"
issueTrackerURL="https://github.com/MasterGeneral156/Mo-Glowstone-Lamps/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
modId="thismeanswar" #mandatory
version="0.0.3" #mandatory
displayName="This Means WAR!" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/MoGlowstoneLamps.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/mo-glowstone-lamps" #optional
logoFile="logo.png" #optional
credits="TheMasterGeneral" #optional
authors="TheMasterGeneral" #optional
# The description text for the mod (multi line!) (#mandatory)
description="Its time for war, so lets have some guns, ammo and whatnot."
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.thismeanswar]] #optional
    modId="ctdcore" #mandatory
    mandatory=true #mandatory
    versionRange="[2.1.1,)" #mandatory
    ordering="NONE"
    side="BOTH"